baseURL = "https://lumenated.github.io"
languageCode = "en-us"
title = "Lumenated"
Copyright = "Lumenated is an initiative by Thomas Farla"

[params]
    ga_api_key = "UA-97050896-1" # Google Analytics API key.
    # avatar = "../../img/avatar.jpg" # Image should be square, and roughly 150px x 150px
    # bio = "Insert your bio here. You should write something really whitty and interesting that nobody is ever going to read or care about. But such is life. I really like the look of having a bio snippet on the blog, though. You may have to adjust some CSS styles depending on how long or short your bio is. I didn't make it super resillient."
    github = "http://github.com/lumenated"
    # footer_1 = "Some text here."
    # footer_2 = "Some different text here."
    # footer_3 = "Even more different text here."